### ISSUE TITLE
[ruFix] UTF-8 console plugin cannat hijack the console output

### ISSUE THREAD

**Issue by Malcanteth** [keepcalm/BukkitForge#209]
I use this plugin: https://github.com/toxuin/ruFix and it does nothing

**Comment by SpoonsJTD** [comment]
I was going to try to reproduce this, but I don't speak Russian. :)

**Comment by Malcanteth** [comment]
How may I serve you with this? Plugin is vital for me

**Comment by SpoonsJTD** [comment]
Are there any errors in the log or does it just fail silently? I will take a look at the code, if the vars and such are in Russian, I might need some help xlating. :)

**Comment by SpoonsJTD** [comment]
ruFix depends upon the ServerCommand event which is currently disabled. I am going to create an issue.

**Comment by Malcanteth** [comment]
Plugin is ported and loaded with no errors, but it does not affect the console input or output. You can always count on me if you need `xlation` from Russian.

**Comment by SpoonsJTD** [comment]
Malcanteth, we fixed various chat issues, please recheck this.

**Comment by Malcanteth** [comment]
r249, still not fixed. Thanks for paying attention to my problem anyway.

**Comment by SpoonsJTD** [comment]
Malcanteth, do you happen to know if this works with MCPC?

**Comment by Malcanteth** [comment]
Seems like it does not.

**Comment by various123** [comment]
This plugin doesn't work, and it is quite outdated.

**Comment by alexbegt** [comment]
Maybe fixed?
