### ISSUE TITLE
[Block-click commands] stop working

### ISSUE THREAD

**Issue by Beelzaboss** [keepcalm/BukkitForge#292]
It sometimes happens, dunno if it's random... when I want to use commands such as /Command then u you click on a block to proceed (example: //wand /vtwalk /setregion) they don't wanto work when I click on the block.. this only happens sometimes and the only way to fix this is a server restart, and we are a pretty big server so I can restart everytime :(

**Comment by keepcalm** [comment]
Update - I think I fixed this.

**Comment by Beelzaboss** [comment]
Wow that was fast :+1: 

Will check it out.

**Comment by Beelzaboss** [comment]
Oh sorry I was using    BukkitForge-1.4.7-63.jar, and this still happen, I am sure you will manage to fix it :)

**Comment by Beelzaboss** [comment]
I am not 100% sure but I think worldedit is making my other plugins with with this, but I am not 100% sure so yeah. don't think it's WE please.

**Comment by Beelzaboss** [comment]
aha I think I got it, not sure yet, but when I die it stop working also

**Comment by SpoonsJTD** [comment]
This should be fixed with new player cache.
