### ISSUE TITLE
[GriefPrevention] Multiple issues

### ISSUE THREAD

**Issue by lisim** [keepcalm/BukkitForge#78]
I cant seem to get this plugin to work

it loads fine and i get no real errors, the commands all work and register but the chest placement or golden shovel ussage/stick usage just dose not work, it seems to register the clicks (as doing the rightclick in spawn protected error brings back you are not permitted to build or modify here)

any ideas what could be causing it?

(link to the plugin: http://dev.bukkit.org/server-mods/grief-prevention/ )

**Comment by minecrafter** [comment]
This shares a lot in common with #29 describing issues with WorldEdit's wand not working.

**Comment by keepcalm** [comment]
Yes, a lot of this kind of thing is broken at the moment, I'm working on it

**Comment by Jadedwolf** [comment]
Griefprevention is one of the biggest and best griefprevention plugins around, allows for players to claim land to protect, even support vanilla mods, like protecting engines, etc
Can you give an idea why it does not work atm?

**Comment by keepcalm** [comment]
A lot of Bukkit's events are unsupported in BukkitForge at present - fire spread events, etc. They take time to implement as they involve modifying java bytecode at runtime. So it's happening slowly.

**Comment by lisim** [comment]
Let me know if there is anything we can do to help KC

**Comment by keepcalm** [comment]
Try again with the latest build, we fixed a lot

**Comment by lisim** [comment]
will do we are just doing a kernel upgrade on server

**Comment by Jadedwolf** [comment]
These errors are happening with the latest bukkitforge build. http://pastie.org/5609632

**Comment by keepcalm** [comment]
One more update to build 40 (heh sorry about all these updates)? I think I fixed that already

**Comment by Jadedwolf** [comment]
The console errors are gone, however claiming land to protect still does not work. Which really is the point of this plugin, easy, friendly claiming and protecting of areas in minecraft.

**Comment by Jadedwolf** [comment]
Just getting this one plugin to work natively would put all vanilla mods to shame, would revolutionize how we see vanilla and bukkit mods and completely make running a vanilla server with hundreds possible.

**Comment by Manawyrm** [comment]
I think that plugin needs many events -- which keepcalm hasn't implemented at the moment... 

More to come ;)

**Comment by Jadedwolf** [comment]
The main point I'm trying to convey is, the first plugin mention when tekkit came to be and feed the beast came to be, was Grief prevention, the ability to let users manage protection of there work without needing server admins involved, thus having this working would literally cause a ripple effect in how we run vanilla servers.

**Comment by lisim** [comment]
The Plugin is starting to work KC is doing great work!

We tested and info stick now works

Placeing chests now works (we had to op someone to place hwoever i think thats related to the modifyworld issue

and the golden shovel registers the right clcik but we ouldnt get it to extend a claim yet

**Comment by Manawyrm** [comment]
Yea. The bug with PlayerInteractEvent was kind of unclever :P

**Comment by delsolsi213** [comment]
does giref prevention protects from mining lasers and turtles?

**Comment by keepcalm** [comment]
It should, it will log any breaks as breaks coming from the username that you set in config for modActionUserName.

**Comment by Jadedwolf** [comment]
Yeah but you still can't claim areas properly if at all.

**Comment by delsolsi213** [comment]
thats not true, im using the 1.4.5 version of grief prevention and my players can protect using  the chest protection feature.

**Comment by Jadedwolf** [comment]
You can't adjust claims with the golden shovel.

**Comment by delsolsi213** [comment]
actually you can , its a bit buggy but it works fine, only probelm im having is that players can dupe blocks that are inside a protected area/region the blocks dont break but they do drop the item block.

**Comment by keepcalm** [comment]
Heh. I'll fix that.

**Comment by delsolsi213** [comment]
TY mate :) also can you look into redpower deployers crashing the server XD

**Comment by lisim** [comment]
We tried large scale testing lastnight sadly the expanding of a claim is stil buggy ashell aswell as the fact ppl can dupe 

We also noticed (while 20+ ppl were trying to claim) that the Blowstone overlay was very buggy aswell as soem claims just randomly unclaimed themselves

**Comment by delsolsi213** [comment]
the duping from protected areas is fixed in the latest build.

**Comment by Jadedwolf** [comment]
No, if you try and break buildcraft blocks in the claim it still drops them and ,leaves the block....

**Comment by lisim** [comment]
But seems fixed for Vanila which is a good start =D

**Comment by MatadorPants** [comment]
Just confirming that the weirdness w/ GriefPrevention continues in the latest builds.

**Comment by RubyRezal** [comment]
Testing with Grief Prevention 7.3 and BukkitForge-1.4.7-151.jar

Functions confirmed working: 
- Placing first chest creates the default first claim
- Griefed tree removal
- Griefed tree replanting
- restorenature function (slash commands appear to be working, but I haven't tested them completely)
  -- Note: restore nature requires tool use and may be subject to the tool bug described below.
  --- (The tool bug appears to send the tool command twice, first with the correct coordinate followed almost instantly by x0 z0 [y0?])

Functions working but bugged:
- Using investigation tool (STICK)
  -- Right clicking a block in claimed land generates two responses
  --- "That block has been claimed by..." and "No one has claimed this block."
  -- Right clicking a block in unclaimed land generates two, "No one has claimed this block," responses.
  --- I assume this function suffers from the same bug described below.
- Using claim creation tool (GOLD_SPADE)
  -- On a claim corner this generates the "Resizing claim..." message instantly followed by "You don't have enough blocks... need [very large number] more"
  Alternately a 'Must be larger than 10x10...' may be shown instead of the not enough blocks message.
  --- The responses are consistent when attempting to move the same corner, which indicates to me Grief Prevention receives two sets of commands and coordinates on the same click, one being the actual block where the player wants to edit a claim, the other being a static location.
  --- I gave myself 80000 bonus claim blocks and created a new claim starting at x110 z354.  The opposite corner appears at x0 z0.
  --- I abandoned all claims and retested multiple times in the area of x0 z0.  The second corner always appears at or within a 2 block radius of this coordinate, usually at x0 z0.

Functions not working:
- Prevention of Explosions & Fire spread on both wild and claimed blocks.
- Prevention of Water and Lava spread into/out of claimed areas.
- Griefing by Mob (Enderman can steal blocks, Creepers and Ghast still blow stuff up, etc...)

Untested:
I am not able to test multiplayer protection at this time.

**Comment by krisdestruction** [comment]
Grief Prevention 7.4 and BukkitForge-1.4.7-175 .jar
Fixed:
--- "That block has been claimed by..." and "No one has claimed this block."
--- Right clicking a block in unclaimed land generates two, "No one has claimed this block," responses.

Bugged:
-- Right clicking a block in claimed land generates two responses: "That block has been claimed by..." x 2

**Comment by ghost** [comment]
"--- Right clicking a block in unclaimed land generates two, "No one has claimed this block," responses."

Seems that broke with the 1.4.7-187 jar. I just installed BukkitForge and Griefprevention's latest build and I get two messages. 

Every bug fix is appreciated, I'm not opening my server without a functional Griefprevention. =D No idea how else to help. Xasta up there pretty much posted everything I noticed as well.

Edit, same stuff going on with build 190. (Previously 187)

**Comment by RubyRezal** [comment]
Grief Prevention 7.4 and BukkitForge-1.4.7-190.jar
Still Bugged:
- All Claim tools actions

Using claim tools (Defaults: Stick and Gold Shovel) calls the associated function(s) twice, once with the proper coordinate then again with a random coordinate at or near x0 z0.

Note: The called functions are working properly, they are just being called incorrectly.  No errors appear in log but tool behavior in game is incorrect.

A note on prior observations in https://github.com/keepcalm/BukkitForge/issues/226
It is possible to create and resize claims by making the double command bug perform invalid actions on the x0 z0 execution.
For example; go to the block at coordinate (10,10) and use the gold shovel to start a claim.  This action will actually create a claim using the selected block and a corner at (0,0) as though the player had walked over there and claimed the second corner.  This bug is reliably reproducible.
Message responses from Grief Prevention should say "Claim created!..." followed by "Resizing claim..."
It is now possible to move the (0,0) corner to another location.  Move to (20,20) and set the new corner.

Now there should be a claim from (10,10) to (20,20).  Messages from GP will say "Claim Resized..." followed by "Claim corner set!...".  Again something in BukkitForge has sent the action a second time using coordinates (0,0) and has started a new claim.

Now move to (30,30) and right click with the gold shovel to complete the claim.  This gives responses "Your selected area overlaps an existing claim," because a claim from (0,0) to (30,30) would overlap with the existing claim, and "This claim would be too small..." because Grief Prevention has again received an erroneous second action at (0,0).

As observed in https://github.com/keepcalm/BukkitForge/issues/344, switching the active hotbar slot does not cancel the current claim activity.

**Comment by keepcalm** [comment]
OK, thanks for the detailed info. I will look into fixing your observed bugs.

**Comment by lisim** [comment]
Once this is sorted BukktiForge will really be perfect for us

**Comment by krisdestruction** [comment]
Really looking forward to this. GP is a great plugin to work with and will be helpful for FTB.

**Comment by acyrid** [comment]
An option for this plugin to correct the fire spread issue temporarily might actually be to make a small change to the plugin itself by having it automatically cancel all fire events rather than let them burn and attempt to stop damage / spread... Once BukkitForge has achieved better fire spread/damage control this change could easily be reverted back.  Just a thought and trying to be helpful thanks for the great work you guys are doing.

**Comment by RubyRezal** [comment]
Changing the plugin wouldn't have any effect, it already works properly on CraftBukkit.  The problem with fire, lava, and water spread is BukkitForge is not yet able to send those events to plugins.

We just need to wait patiently as BukkitForge is developed and thank keepcalm and all other developers involved for the amazing working being done.

**Comment by acyrid** [comment]
Gotcha, I only recently returned to admining/developing for minecraft and discovered this. So I definitely dont have an intimate knowledge of BF yet.

**Comment by krisdestruction** [comment]
Basically the functionality is there on GP but the API isn't hooked up from bukkit to forge through bukkitforge yet?

**Comment by RubyRezal** [comment]
Essentially, yes.  As I understand it BukkitForge has yet to implement the spread events portion of Bukkit API.

I could probably build a temporary solution using block break events and a block scanning loop I built for another plugin... but it would only be able to trigger after fire has caused damage.  It would be a horrible kludge, much less graceful than GP and probably bog down servers with unnecessary block scanning every time a burnable block was broken.  I really don't want to be responsible for crashing servers just to provide a temporary workaround.

Better we wait for BukkitForge to add support for spread events.

**Comment by krisdestruction** [comment]
Instead of implementing a temp solution, why not do the API mapping instead? I don't expect bukkit -> Forge to be 1:1 but there should be many similarities right?

**Comment by RubyRezal** [comment]
As I said, a temp solution really isn't a solution.  I'm not sure I understand your suggestion.  It is my understanding that the BukkitForge project intends to fully implement the Bukkit API as a Forge mod, so the goal is to be 1:1.
(You may be thinking of ForgeEssentials which is attempting to emulate popular Bukkit plugins rather than allowing Bukkit plugins to run on Forge servers.)

Unfortunately I am not involved in development of BukkitForge and do not feel experienced enough with Java to contribute substantially to a project of this magnitude.  I am working on much smaller projects for now and learning as I go.

I suggest that we have gotten off topic and should wait for updates from the BukkitForge team regarding these issues.

**Comment by Sageavatar** [comment]
Anyone have a status update?

Thanks.

**Comment by Sageavatar** [comment]
Tried today with BF Build 230 and GP 7.6.1. As far as I could tell, still not working. 
Observations:
- Initial Chest placement yields message, but no area markers
- String does not show claims
  -Gold shovel will place first corner, but thinks you're trying to select a very large area.
- Gold Shovel does not "Ready" and "Lower" properly but that's another Issue ( #344 )

**Comment by ghost** [comment]
Is this currently being worked on?

**Comment by RubyRezal** [comment]
Note: all coordinates in the post below are in x,y,z format in accordance with Minecraft's use of this system. i.e. x is North or South, Y is layer, Z is East or West.  Where the coordinate letter appears the actual value is unknown.

keepcalm acknowledged my observations in a previous post, the development team is aware of and working on these issues.

BukkitForge is being improved daily, watch the change log for updates at http://build.technicpack.net:8080/job/BukkitForge/changes

There are very many things that need to be addressed, we just need to be patient.

@Sageavatar - String is no longer the default investigation tool for Grief Prevention since it can now be placed in the world for use as a tripwire (as of MC 1.3).  This change was made by GP's developer(s).  This may conflict with WorldEdit/WorldGuard if you also have them installed.  Check the config file for Grief Prevention to make sure you are using the correct tool, change the tool ID if necessary to avoid a conflict with other plugins.  Note that Grief Prevention requires the numeric ID of the tool and will not accept item names like "STICK". (See my notes in previous posts.)

Also, please see my account of the tool command duplication bug in my posts above.  BukkitForge appears to tell Grief Prevention the tool has been used twice every time it is used once; the first tool execution is correct, the second execution is a bug and sends an apparently random coordinate at or near (0,y,0).
I am not aware if this bug affects other plugins, but I would assume it does.

I tried to work around this bug by creating a claim containing (0,y,0) and changing that claim's owner in the data files.  Unfortunately this does not allow the tools to be used even though previous experiments showed I could perform invalid actions on the erroneous second command in order to move a claim away from (0,y,0).

@keepcalm Interesting note - Shift-Right-Clicking on a chest with a GP tool in hand sends only the incorrect command.  This is somewhat consistent with GP running on a CraftBukkit server where Shift-Right-Click on a block with inventory does not execute tool use.

I suspect PlayerInteract (or some variation thereof) is being called in two places in the BukkitForge code.  I have downloaded the sources for BukkitForge and Grief Prevention.  I will look for the error as I am able.  Unfortunately there is a lot to look at and I'm not exactly familiar with Forge, but I'll give it a shot.

**Comment by krisdestruction** [comment]
Heads up, this plugin is now maintained by Tux2

**Comment by RubyRezal** [comment]
Tux2 is maintaining GP for Bukkit/CraftBukkit.  As far as I know Tux2 is not involved with BukkitForge.

The issues reported here are specific to running the plugin on BukkitForge and should not be taken to Tux2 unless they also appear on a CraftBukkit server.

**Comment by krisdestruction** [comment]
Yes I know, but my experience is that Tux2 is much more workable than bigscary. If there's anything on the bukkit end, he's usually more open to discussion.

**Comment by Biblo** [comment]
delsolsi213 commented 7 months ago:
does giref prevention protects from mining lasers and turtles?

 keepcalm commented 7 months ago:
It should, it will log any breaks as breaks coming from the username that you set in config for modActionUserName.

How does it work? I can break blocks in claims with the mining laser.

**Comment by Luminator97** [comment]
Its 2017 (Almost 2018) guys, and I'm having trouble with the plugin. I have searched and searched, but I couldn't find a solution to my problem. I added the plugin, but it doesn't let me build outside of claims unless I do /ignoreclaims. I went into the config file and didn't find anything. Then I went to youtube and found a video that could help, but it was outdated and the information was useless. If anybody knows how to fix this, I would greatly appreciate it. (BTW, it says I can't build because I need to claim some land first, which I did, about 10 times)
